### ISSUE TITLE
Markbot Fun

### ISSUE THREAD

**Issue by aylalab** [aylalab/action-hero-card-with-actions#1]
Hey! 

Just a reminder to please take a look at this for me, Markbot is still stuck on a 20% difference at the 400px screen size.

Thanks! :)

@charlie-quinn

**Comment by charlie-quinn** [comment]
@aylalab most students are struggling with this assignment so we are going to do a quick walkthrough in class together this week.

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`
